-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Author"
(
    author_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    "Email" character varying(50),
    "City" character varying(50),
    "Country" character varying(50),
    PRIMARY KEY (author_id)
);

CREATE TABLE IF NOT EXISTS public."Borrower"
(
    borrower_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    "Email" character varying(50),
    "Phone" character varying(50),
    "Address" character varying(50),
    "City" character varying(50),
    "Country" character varying(50),
    PRIMARY KEY (borrower_id)
);

CREATE TABLE IF NOT EXISTS public."Book"
(
    book_id integer NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Edition" integer,
    "Year" integer,
    "Price" numeric(4, 2),
    "Pages" integer,
    PRIMARY KEY (book_id)
);

CREATE TABLE IF NOT EXISTS public."Author List"
(
    author_id integer NOT NULL,
    book_id integer NOT NULL,
    role character varying(100)
);

CREATE TABLE IF NOT EXISTS public."Copy"
(
    copy_id integer NOT NULL,
    book_id integer NOT NULL,
    "Status" character varying(25),
    PRIMARY KEY (copy_id)
);

CREATE TABLE IF NOT EXISTS public."Loan"
(
    copy_id integer NOT NULL,
    borrower_id integer NOT NULL,
    loan_date date,
    return_date date,
    load_days integer
);

ALTER TABLE IF EXISTS public."Author List"
    ADD FOREIGN KEY (book_id)
    REFERENCES public."Book" (book_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Author List"
    ADD FOREIGN KEY (author_id)
    REFERENCES public."Author" (author_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Copy"
    ADD FOREIGN KEY (book_id)
    REFERENCES public."Book" (book_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Loan"
    ADD FOREIGN KEY (copy_id)
    REFERENCES public."Copy" (copy_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Loan"
    ADD FOREIGN KEY (borrower_id)
    REFERENCES public."Borrower" (borrower_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;