-- MySQL Script generated by MySQL Workbench
-- Wed Nov 29 22:20:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema monitoring_optimization
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema monitoring_optimization
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `monitoring_optimization` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `monitoring_optimization` ;

-- -----------------------------------------------------
-- Table `monitoring_optimization`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoring_optimization`.`departments` (
  `dep_no` CHAR(4) NOT NULL,
  `dept_name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`dep_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monitoring_optimization`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoring_optimization`.`employees` (
  `emp_no` INT NOT NULL,
  `birth_date` DATE NOT NULL,
  `first_name` VARCHAR(14) NOT NULL,
  `last_name` VARCHAR(16) NOT NULL,
  `gender` ENUM('M', 'F') NOT NULL,
  `hire_date` DATE NOT NULL,
  PRIMARY KEY (`emp_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monitoring_optimization`.`dept_emp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoring_optimization`.`dept_emp` (
  `from_date` DATE NOT NULL,
  `to_date` DATE NOT NULL,
  `departments_dep_no` CHAR(4) NOT NULL,
  `employees_emp_no` INT NOT NULL,
  PRIMARY KEY (`departments_dep_no`, `employees_emp_no`),
  INDEX `fk_dept_emp_departments1_idx` (`departments_dep_no` ASC) VISIBLE,
  INDEX `fk_dept_emp_employees1_idx` (`employees_emp_no` ASC) VISIBLE,
  CONSTRAINT `fk_dept_emp_departments1`
    FOREIGN KEY (`departments_dep_no`)
    REFERENCES `monitoring_optimization`.`departments` (`dep_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dept_emp_employees1`
    FOREIGN KEY (`employees_emp_no`)
    REFERENCES `monitoring_optimization`.`employees` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monitoring_optimization`.`salaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoring_optimization`.`salaries` (
  `salary` INT NOT NULL,
  `from_date` DATE NOT NULL,
  `to_date` DATE NOT NULL,
  `employees_emp_no` INT NOT NULL,
  PRIMARY KEY (`from_date`, `employees_emp_no`),
  INDEX `fk_salaries_employees1_idx` (`employees_emp_no` ASC) VISIBLE,
  CONSTRAINT `fk_salaries_employees1`
    FOREIGN KEY (`employees_emp_no`)
    REFERENCES `monitoring_optimization`.`employees` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monitoring_optimization`.`titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoring_optimization`.`titles` (
  `title` VARCHAR(45) NOT NULL,
  `from_date` DATE NOT NULL,
  `to_date` DATE NULL,
  `employees_emp_no` INT NOT NULL,
  PRIMARY KEY (`from_date`, `title`, `employees_emp_no`),
  INDEX `fk_titles_employees1_idx` (`employees_emp_no` ASC) VISIBLE,
  CONSTRAINT `fk_titles_employees1`
    FOREIGN KEY (`employees_emp_no`)
    REFERENCES `monitoring_optimization`.`employees` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monitoring_optimization`.`dept_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoring_optimization`.`dept_manager` (
  `from_date` DATE NOT NULL,
  `to_date` DATE NOT NULL,
  `employees_emp_no` INT NOT NULL,
  `departments_dep_no` CHAR(4) NOT NULL,
  PRIMARY KEY (`employees_emp_no`, `departments_dep_no`),
  INDEX `fk_dept_manager_employees1_idx` (`employees_emp_no` ASC) VISIBLE,
  INDEX `fk_dept_manager_departments1_idx` (`departments_dep_no` ASC) VISIBLE,
  CONSTRAINT `fk_dept_manager_employees1`
    FOREIGN KEY (`employees_emp_no`)
    REFERENCES `monitoring_optimization`.`employees` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dept_manager_departments1`
    FOREIGN KEY (`departments_dep_no`)
    REFERENCES `monitoring_optimization`.`departments` (`dep_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
