-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."DimCustomer"
(
    customer_id character varying(10) NOT NULL,
    first_name character varying(25),
    last_name character varying(25),
    customer_name character varying(50),
    gender character varying(25),
    PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public."DimCustomerProfile"
(
    profile_id character varying(10) NOT NULL,
    month_as_member integer,
    education character varying(25),
    marital_status character varying(25),
    PRIMARY KEY (profile_id)
);

CREATE TABLE IF NOT EXISTS public."DimLocation"
(
    location_id character varying(10) NOT NULL,
    country character varying(25),
    province_or_state character varying(25),
    city character varying(25),
    location_code character varying(25),
    PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS public."DimGeoLocation"
(
    geo_loc_id character varying(10) NOT NULL,
    latitude numeric(8, 6),
    longitude numeric(9, 6),
    postal_code character varying(25),
    PRIMARY KEY (geo_loc_id)
);

CREATE TABLE IF NOT EXISTS public."DimLoyalty"
(
    loyalty_id character varying(10) NOT NULL,
    loyalty_number bigint,
    loyalty_statue character varying(25),
    loyalty_count boolean,
    PRIMARY KEY (loyalty_id)
);

CREATE TABLE IF NOT EXISTS public."DimProduct"
(
    product_id character varying(10) NOT NULL,
    product_line character varying(50),
    coupon_response character varying(25),
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public."DimTime"
(
    time_id character varying(10) NOT NULL,
    order_year integer,
    quarter character varying(3),
    PRIMARY KEY (time_id)
);

CREATE TABLE IF NOT EXISTS public."FactSales"
(
    sales_id character varying(10) NOT NULL,
    customer_id character varying(10),
    location_id character varying(10),
    geo_loc_id character varying(10),
    profile_id character varying(10),
    time_id character varying(10),
    product_id character varying(10),
    loyalty_id character varying(10),
    income bigint,
    quantity integer,
    unit_sale_price bigint,
    unit_cost bigint,
    revenue bigint,
    customer_lifetime_value numeric(10, 3),
    PRIMARY KEY (sales_id)
);

ALTER TABLE IF EXISTS public."FactSales"
    ADD FOREIGN KEY (customer_id)
    REFERENCES public."DimCustomer" (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactSales"
    ADD FOREIGN KEY (location_id)
    REFERENCES public."DimLocation" (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactSales"
    ADD FOREIGN KEY (geo_loc_id)
    REFERENCES public."DimGeoLocation" (geo_loc_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactSales"
    ADD FOREIGN KEY (profile_id)
    REFERENCES public."DimCustomerProfile" (profile_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactSales"
    ADD FOREIGN KEY (time_id)
    REFERENCES public."DimTime" (time_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactSales"
    ADD FOREIGN KEY (product_id)
    REFERENCES public."DimProduct" (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactSales"
    ADD FOREIGN KEY (loyalty_id)
    REFERENCES public."DimLoyalty" (loyalty_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
	
COMMIT;

END;